### PR TITLE
massive speed increase for mapping construction

### LINKED ISSUE #78: Opening a large yaml file is very slow
this line:
```
auto yamlRoot = Loader("typeIDs.yaml").load();
```
Is taking multiple minutes. 

Parsing the file using [YamlDotNet](https://github.com/aaubry/YamlDotNet) is a matter of seconds:

```
var yaml = new YamlStream();
yaml.Load(new StreamReader("typeIDs.yaml"));
```

(For both libraries then iterating over the data is about equally fast)

Check the [Eve Online Static Data Export](https://developers.eveonline.com/resource/resources) for some large files to test

### PR DESCRIPTION
**Pull request by Herringway**
It ended up being a lot simpler than I guessed!
Instead of checking for uniqueness on every insertion, we now do one check after the insertions are complete. I believe this reduces the complexity from O(n^2) to O(n log n) - a massive savings!

Fixes #78!

### CODE REVIEW

**Comment by Herringway** [comment]
It should be noted that this will now just reject duplicate keys instead of silently ignoring them, but since yaml explicitly disallows mappings with duplicate keys, that's probably for the best.

**Comment by BBasile** [comment]
I don't think it's necessary to wait much more before merging this important fix. Just one think i forgot: Is it possible to add a unittest with `assertThrown` and `assertNotThrow` ?

**Comment by BBasile** [comment]
so these tests ?

**Comment by Herringway** [comment]
don't think I can easily add a unittest block to test this code specifically, but I added an invalid doc to the test suite.

**Comment by BBasile** [comment]
Non required CI checks block the dlang bot apparently.

**Pull request merged**
