### PR TITLE
Replace stream-based dumping interface with an outputrange-based interface

### PR DESCRIPTION
**Pull request by Herringway**
I'm not completely satisfied with the interface yet, but I'd like to hear some thoughts on the work done so far.

Current version shows a massive runtime improvement - a document that currently takes 40 seconds to dump now takes only 7 seconds.

Would like to hear thoughts on:
- Whether or not `@system` ranges should be explicitly supported
  - This would require some major changes to `dyaml.emitter`
- Whether or not a `fileDumper` function or equivalent should be added

### CODE REVIEW

**Comment by BBasile** [comment]
Can't an Appender be used ? Outbuffer is a dusty phobos module.

**Comment by Herringway** [comment]
Appender shouldn't be an issue as long as it's an `OutputRange`.

**Comment by BBasile** [comment]
It is.

**Comment by Herringway** [comment]
Removed outbuffer, added appender.
Have also made encoding a template parameter to dump - this way we can avoid writing encodings to ranges that don't support that encoding.

**Comment by BBasile** [comment]
this one needs rebase now.

**Pull request merged**
