### PR TITLE
rework with mir

### LINKED ISSUE #249: Loss of precision when representing reals
Real values are represented with the `%12f` format specifier, which in many cases is insufficient, because it has only 6 decimal places.

### LINKED ISSUE #270: double is a better then real
Excess precision cause looses in precision when converted to/form decimal representation. Almost all other non D YAML implementations uses double.

### PR DESCRIPTION
**Pull request by 9il**
- replace `real` with `double` to match other implementations: excess precision is bad when one need precise serialisation, fixes #270 
- use mir to/from string for floating point numbers, fixes #249 
- replace SysTime with Timestamp, arbitrary timestamp precision is supported now. For example, one can de/serialise `Date` without additional time. `master` can serialise only full precision timestamps.
- added mir engine de/serialisation support for `Node`

### CODE REVIEW

**Comment by Herringway** [comment]
I'd rather not introduce new dependencies to DYAML.

**Comment by 9il** [comment]
We need this changes or a fork. I expect that the fork will dominate after a while because of Symmetry.

**Comment by Herringway** [comment]
I cannot accept a dependency as large as mir-algorithm. This is not something I can maintain alone. There are also a large number of seemingly-irrelevant changes, such as the inclusion of an output.yaml, a submodule that appears to be unused, and private symbols being made public.

Threatening to fork will not address any of these issues. Competition is welcome.

**Comment by 9il** [comment]
I hope you will change you mind. You wouldn't be alone I think.

**Pull request closed without merging**
