### PR TITLE
Fix compilation with DMD 2.072.0

### PR DESCRIPTION
**Pull request by ZombineDev**
The following DMD PRs added more rigorous safety checks directly
affecting this project:
* dlang/dmd#5852 (fix Issue 15399 - unaligned pointers are not `@safe`) - triggered at line:
  https://github.com/kiith-sa/D-YAML/blob/v0.5.3/source/dyaml/emitter.d#L1011

* dlang/dmd#5940 (Unions may break immutability / unions with pointers are un-`@safe` ) - triggered at line:
  https://github.com/kiith-sa/D-YAML/blob/v0.5.3/source/dyaml/event.d#L230

* dlang/dmd#5876 (Casting from `void[]` to `T[]` is erroneously considered `@safe`) - triggered at line:
  https://github.com/kiith-sa/D-YAML/blob/v0.5.3/source/dyaml/loader.d#L186

* dlang/dmd#5860 (array.ptr in @safe code may point past end of array) - triggered at line:
  https://github.com/kiith-sa/D-YAML/blob/v0.5.3/source/dyaml/zerostring.d#L35

### CODE REVIEW

**Comment by davispuh** [comment]
👍

**Comment by kozhevnikov-peter** [comment]
Unfortunately, the author of the project does not respond to merge requests. 
I had to create a new package [yaml-d](https://code.dlang.org/packages/yaml-d). Please do not judge me. Let's develop Dlang.

**Comment by wilzbach** [comment]
@kozhevnikov-peter FWIW I had the idea to put vital components to the D ecosystem in a D community hub, so that such maintainance work doesn't require forking a package every now and then. Please see:

https://github.com/d-martians/discussions/issues/2

I am happy to send out invitations to the GitHub organization in case you (or others) are interested in this idea.

**Comment by kozhevnikov-peter** [comment]
@wilzbach This is a great idea. I agree to participate in this.

**Comment by wilzbach** [comment]
@ZombineDev you should now have permissions to finally move this forward ;-)

**Pull request closed without merging**
