### PR TITLE
Fix #184: Support for DIP1000

### LINKED ISSUE #184: Fix compilation errors with -dip1000
Some are simple - scope on some parameters, etc.

Others are not. Something weird is going on with -dip1000 and dyaml.emitter - the delegates created there appear to gain random attributes (const delegates? nothrow delegates that call enforce() without issue? what...?) and require explicit casting to their real type to work as expected.

RedBlackTree is also unusable `@safe`ly when -dip1000 is specified.

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by Herringway** [comment]
We can't use -preview=dip1000. It'll be inherited by everything depending on D-YAML. We can't force that on the users yet. I think it would be a good idea to have the CI testing with it on and off, though

**Comment by Geod24** [comment]
Agreed. Will add a `configuration` for it.

**Comment by Geod24** [comment]
@Herringway : Looks like this is finally green

**Comment by Geod24** [comment]
Fix the compiler and Phobos, which is in progress...

**Comment by Geod24** [comment]
So I guess it's time for a new release, as soon as I confirm it works with `dub`.

**Comment by PetarKirov** [comment]
@Geod24 could we have instead used https://github.com/pbackus/sumtype from dub?

**Comment by Geod24** [comment]
We have to vendor D-YAML / Configy, so I don't see why we wouldn't have to vendor sumtype ?

**Comment by PetarKirov** [comment]
I meant using the sumtype Dub package, instead of vendoring it here. But I now see that you had to that because D-YAML is/will be vendored in Dub itself. Can't we require using the previous version of Dub to build the current one?

**Comment by Geod24** [comment]
I would have to raise the bug fix to the dub package, wait for a release, and force potential users to use that release or higher.
It's a solution I didn't consider, honestly, because I expect most changes in the future will target `std.sumtype` and forget about the dub package. I don't think it would have that much of a positive impact.

**Comment by PetarKirov** [comment]
> I would have to raise the bug fix to the dub package, wait for a release

I see where you're coming from. That said, @pbackus is usually relatively quick in porting bug fixes from Phobos to his repo. See: https://github.com/pbackus/sumtype/tags

**Comment by pbackus** [comment]
I was slow on this one, but I've got it merged now and tagged as `v1.2.6`. Should be available on dub soon.

**Pull request merged**
